### ISSUE TITLE
手动点开红包后，会被自动返回

### ISSUE THREAD

**Issue by gaupen1186** [geeeeeeeeek/WeChatLuckyMoney#101]
最新版2.1.1，手动点开红包后，会被自动返回，之前的2.0.1没有此问题。
android 4.4.2  MIUI 7

**Comment by ray26** [comment]
@gaupen1186 能不能详细解释一下什么叫自动返回，返回到哪里

**Comment by HKOYES** [comment]
就是没有停留在看到抢了多少，自动返回聊天界面了

**Comment by ray26** [comment]
@HKOYES 这是正常的

**Comment by gaupen1186** [comment]
手动点开的红包，不应该给自动返回吧？
应该是自动点开的红包给自动返回，手动点开的红包，需手动返回。
现在我想看下别人抢了多少都不行了。

**Comment by ray26** [comment]
都是这样的，目前只能后台杀掉进程解决
