### ISSUE TITLE
抢红包规避大小

### ISSUE THREAD

**Issue by chendd** [geeeeeeeeek/WeChatLuckyMoney#104]
IOS版听说抢红包可以规避最大和最小的红包，真的可以吗？有研究过没，可不可加入下个版本的新功能。。。

**Comment by geeeeeeeeek** [comment]
不可以，反正我是不信的

**Comment by chendd** [comment]
其实我也不怎么信的，简单说下我的想法：控制红包大小的因子a应该是服务端随机发送下来的，并且分成n个红包的因子a总和为1，但如果我们可以修改因子a=1/n的话这样抢到的红包就不是最大也不是最小(n>2时，证明就不说了)。现在有用hook基于Xspoed的微信猜拳、骰子点数作弊(https://github.com/chendd/WeChatHook)，不太清楚这个骰子、猜拳跟微信红包控制大小的原理是否相同，如果相同应该也可以这样作弊。。。

**Comment by geeeeeeeeek** [comment]
你去知乎上看看好像有红包金额的算法，有点出入。这个插件是基于模拟点击的，做不到hook微信的方法。
