### ISSUE TITLE
nexus6 android 6.0 锁屏时不能抢红包

### ISSUE THREAD

**Issue by wei-yao** [geeeeeeeeek/WeChatLuckyMoney#105]
2016.1.31 的 stable 版本，nexus6， android 6.0 开启了息屏抢红包的功能，
关闭锁屏成功，但是锁屏时不能抢红包

**Comment by wei-yao** [comment]
其他手机也试了，锁屏抢红包的功能不是特别稳定

**Comment by ray26** [comment]
是的，现在这个功能还不是特别稳定，请期待以后更新(๑>؂<๑）
