### ISSUE TITLE
ZTE Nubia Z7 (Android 4.4.2)抢红包失败

### ISSUE THREAD

**Issue by liyayun** [geeeeeeeeek/WeChatLuckyMoney#11]
`努比亚z7``android4.4.2`抢红包失败
我用的stable分支，在应用安装后，首次进入群聊可以正常运行一次。一旦抢过一次，再也不能用了，除非卸载重装。

**Comment by geeeeeeeeek** [comment]
今天刚把#9 Android6.0的复现了。然而努比亚。。不是不想修啊。。是完全不知道在别的平台上发生了什么。。适配是个坑
