### ISSUE TITLE
新版本点不开红包详情的问题

### ISSUE THREAD

**Issue by jason1290** [geeeeeeeeek/WeChatLuckyMoney#110]
新版本抢红包很不错，现在有个小问题，就是点不开红包详情，每次一打开红包要看详情，就自动关闭，能否设置自己点击开的红包或者已经领过的红包不自动关闭吗？

**Comment by geeeeeeeeek** [comment]
@jason1290 下个版本。4号吧。

**Comment by jason1290** [comment]
好的，辛苦您了
