### ISSUE TITLE
现在最新的又出现重复抢同一个红包了

### ISSUE THREAD

**Issue by 2767321434** [geeeeeeeeek/WeChatLuckyMoney#111]

**Comment by ray26** [comment]
没有这个情况出现捏，你的意思是不是重复返回了

**Comment by 2767321434** [comment]
还是有，上午最新下载下来编译的，会不会和系统版本有关系啊，我是miui7，安卓5.0的

**Comment by ray26** [comment]
@2767321434 我miui体验版，android6.0没问题，你不要自己编译，你下载release自己试试

**Comment by 2767321434** [comment]
意思代码和现在的不一样？不是重复返回，是重复抢同一个红包，从点开到返回，一直重复

**Comment by ray26** [comment]
不是，你下载release版本，不要自己编译，我觉得有可能是你studio的问题

**Comment by 2767321434** [comment]
好吧，我试试，感觉都一样吧
