### ISSUE TITLE
关于微信红包封号的思考

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/WeChatLuckyMoney#112]
最近我做了一个测试，发现微信红包封号只是进行了前段的限制，如果我们能做到在xposed框架的支持下，做到不打开拆红包的那个界面的情况下完成拆开红包的动作，就可以突破微信封号限制

**Comment by ray26** [comment]
做了测试，拿了个被封的号，在不打开拆红包的界面就完成了拆红包，是可以的

**Comment by geeeeeeeeek** [comment]
装XPosed框架挺麻烦的

**Comment by HKOYES** [comment]
别人说苹果封了号也能抢，可能就是你说的这种

**Comment by ray26** [comment]
@geeeeeeeeek 也不麻烦，刷个包装个apk就行了，目前android突破封号只有这个办法

**Comment by yiranshaxiao** [comment]
@ray26 最近我做了一个测试，发现微信红包封号只是进行了前段的限制，如果我们能做到在xposed框架的支持下，做到不打开拆红包的那个界面的情况下完成拆开红包的动作，就可以突破微信封号限制

1、你的意思是，号被封了，继续抢红包？不太可能这种限制只在前端，而服务端没有，怎么测试的？
2、不妨讨论下，微信的封号机制是怎么运作的，去防止封号的发生。
3、Xposed框架下面的已经有现成的，不过在最新版的微信上无法使用，需要自己写：）

**Comment by geekvape** [comment]
封号是如何检测的？

**Comment by progmboy** [comment]
@yiranshaxiao xposed的插件最新的也可以用吧,看这里。https://github.com/qingyan1990/luckymoney
同问微信封号进行前段的限制是啥意思？

**Comment by progmboy** [comment]
我感觉他检测是不是就是仅仅检测安装的app的名称呢

**Comment by ray26** [comment]
最在测试一个xposed框架，最新微信支持的，不是你们开源的那个，不开源，我到时jadx反编译一下看一下其代码，反正我测试这边在封号情况下是可以抢的的，去聊天室细谈

**Comment by ray26** [comment]
@yiranshaxiao

**Comment by xfunforx** [comment]
还在用辅助？？这速度和xposed的速度不在一个等级中。
