### ISSUE TITLE
判重逻辑问题

### ISSUE THREAD

**Issue by xky183** [geeeeeeeeek/WeChatLuckyMoney#114]
相同的人发的相同的留言的红包是会被跳过检查的，你试试。比如我自己连续发的【恭喜发财，大吉大利！】这样的红包，第二个开始不会自动拆。改下留言就可以拆了。

**Comment by ray26** [comment]
酷派s6和中兴的没用，因为目前只支持android4.4（api22）及以上。哪个是荣耀的问题

**Comment by xky183** [comment]
老大 你的意思是API22以上  非荣耀是可以的？
那我赶紧换个试试

**Comment by ray26** [comment]
我是问哪些是荣耀出现的问题

**Comment by xky183** [comment]
只尝试了荣耀4X （前面说错了，不是5X是4X）  电信定制版，厂家型号是CHE1-CL10，系统是android4.4.4   华为的EUI3.0
另外刚才测试了三星 note3电信版   型号是N9009  版本是Android5.0

**Comment by xky183** [comment]
三星的note3也不行，上面没说清楚

**Comment by xky183** [comment]
问题都一样

**Comment by xky183** [comment]
请问你用的什么手机？

**Comment by ray26** [comment]
哪个问题，全部问题吗

**Comment by xky183** [comment]
只测了聊天界面
聊天界面下，第一个包打开了，但是没拆；
然后第二个包就不再自动打开了，
跟之前其他手机还有区别是“：手动打开它也不自动拆（其他手机是手动打开会自动拆）

**Comment by xky183** [comment]
请问现在有哪些测试确定OK的手机呢？

**Comment by xky183** [comment]
我也试了V2.0.1版本也有是同样的情况，可以抢几个  后来就不行了

**Comment by ray26** [comment]
我测试一下

**Comment by Pengchengistaken** [comment]
相同的人发的相同的留言的红包是会被跳过检查的，你试试。比如我自己连续发的【恭喜发财，大吉大利！】这样的红包，第二个开始不会自动拆。

**Comment by ray26** [comment]
谢谢反馈

**Comment by ray26** [comment]
确实有这个问题

**Comment by zhaoyz6910** [comment]
确实有这个问题
