### ISSUE TITLE
帮助与反馈建议跳转到系统自带的浏览器

### ISSUE THREAD

**Issue by htc550605125** [geeeeeeeeek/WeChatLuckyMoney#119]
系统自带浏览器有cookie，并且在自动更新无法下载的时候无法通过app内的issue到内置浏览器下载。

**Comment by ray26** [comment]
最新版已经支持跳转到系统自带浏览器了

**Comment by geeeeeeeeek** [comment]
汪 webview的cookie是开启的，下载的话直接设置里面吧。
