### ISSUE TITLE
急！Flyme上使用失效！

### ISSUE THREAD

**Issue by WangAndy** [geeeeeeeeek/WeChatLuckyMoney#127]
机型：Mi2S W版
OS版本：FlyMe 4.5.1 体验版

在辅助功能中开启后，回到APP中依旧显示“开始插件”

**Comment by WangAndy** [comment]
而且即便开启后，抢红包功能依旧失效，然而我先前使用1.X版本时，抢红包功能正常。

**Comment by geeeeeeeeek** [comment]
和我插件没关系吧，是否有可能是你ROM升级或者其他原因导致的？

**Comment by ray26** [comment]
你把flyme的rom自带的插件关了，刷回正常版本，不要刷新春特别版试试

**Comment by rootphantomer** [comment]
@WangAndy 我这也是flyme，mx4,新春特别版，挺好用的。就是魅族的现在联发科的机子wifi 有断流情况，这个挺烦的。

**Comment by ray26** [comment]
@rootphantomer 不要用新春特别版，用最新版的flyme应该解决了断流问题，这只是一个cpu MT6795出现的问题，没有影响到其他联发科的机子

**Comment by rootphantomer** [comment]
@ray26 这已经是最新的beta版了，难道你说的是日更版本？

**Comment by ray26** [comment]
@rootphantomer 目前联发科给出的解决wifi断流的方法只有升级固件，所以建议你还是去flyme论坛反馈一下

**Comment by rootphantomer** [comment]
@ray26 好的，感谢。🙏
