### ISSUE TITLE
希望fir.im作为固定的墙内下载平台

### ISSUE THREAD

**Issue by cantonadong** [geeeeeeeeek/WeChatLuckyMoney#132]
最新版本还是2.2，严重滞后了。

给没有梯子的同学更新的机会。

**Comment by ray26** [comment]
你去看最新的fir.im,更换了地址了fir.im/luck

**Comment by geeeeeeeeek** [comment]
@cantonadong fir.im下载链接一直有，我会考虑把应用内的地址也换成fir.im。

**Comment by ray26** [comment]
@geeeeeeeeek 更新地址可以切换到fir的项目的，他们提供了插件[fir更新插件](http://bughd.com/doc/android-version-update)

**Comment by geeeeeeeeek** [comment]
@ray26 好我看下
