### ISSUE TITLE
我的手机是魅族3，开启插件，会跳转到辅助功能

### ISSUE THREAD

**Issue by laozhizi** [geeeeeeeeek/WeChatLuckyMoney#134]

**Comment by geeeeeeeeek** [comment]
插件需要在辅助功能中手动开启，由于Android的安全性限制。

具体操作：
点击`开启插件`进入辅助服务，点击`微信红包`
![2 pic](https://cloud.githubusercontent.com/assets/7262715/13056523/df256cdc-d450-11e5-97ff-10d1ccfa389d.jpg)

打开右侧的滑动开关，在弹出的窗口中点击`确定`
![1 pic](https://cloud.githubusercontent.com/assets/7262715/13056521/dcde9b1a-d450-11e5-9d70-52f65d538b7b.jpg)

**Comment by laozhizi** [comment]
Thanks!
