### ISSUE TITLE
webview AccessibilityService

### ISSUE THREAD

**Issue by chendd** [geeeeeeeeek/WeChatLuckyMoney#135]
弱弱问下对于webview写的界面，用AccessibilityService可以模拟操作内部html的控件吗？谢谢！

**Comment by geeeeeeeeek** [comment]
不可以。不太清楚有没有专门的webview-native的bridge来做这件事。

AccessibilityService获取的是View中组件的hierarchy，WebView里面是DOM组件的hierarchy了。
