### ISSUE TITLE
stable - 稳定版Bug

### ISSUE THREAD

**Issue by sheng930920** [geeeeeeeeek/WeChatLuckyMoney#14]
我用stable - 稳定版在魅蓝note2手机上测试，自己发的红包不能自动去抢，别人连续发的多个红包只能抢最后一个

**Comment by geeeeeeeeek** [comment]
这就是预期的效果，不是bug。stable分支是抢最后一个红包的，文档里就是这么写的...

抢自己的红包代码加上了，还没发Release，想跟一些优化一起发，但期末比较忙，你等不及可以自己编译下，虽然我觉得这个不重要。
