### ISSUE TITLE
在某些情况下，打开红包，无法后退。

### ISSUE THREAD

**Issue by wagaman** [geeeeeeeeek/WeChatLuckyMoney#140]
小米NOTE，群30个，电脑微信登陆，手机端扔接受同送的情况下。

收到红包后，点击打开红包后，显示已经被抢空。
在这个界面下，有时不会回退，造成无法抢下一个包。

**Comment by ray26** [comment]
miui现在是存在兼容性问题

**Comment by geeeeeeeeek** [comment]
@ray26 20天前还没有 MIUI 8 吧，我在 MIUI 7 开发版无法复现

**Comment by ray26** [comment]
20天前miui8已经开始小部分内测了

**Comment by geeeeeeeeek** [comment]
@ray26 如果真是 MIUI 8 的锅的话得赶在 17 号之前 fix ……

**Comment by ray26** [comment]
问题就是现在完全不知道到底是哪个任务拦截了，debug看不出异常╭∩╮(︶︿︶)╭∩╮
