### ISSUE TITLE
Flyme OS 4.5.4.1A抢红包失败 

### ISSUE THREAD

**Issue by sheng930920** [geeeeeeeeek/WeChatLuckyMoney#15]
在魅族魅蓝手机上测试最新的稳定版，无论是他人还是自己发的红包都抢不到，抢红包失败

**Comment by geeeeeeeeek** [comment]
留下Android版本 Flyme版本

**Comment by sheng930920** [comment]
Flyme OS 4.5.4.1A

**Comment by geeeeeeeeek** [comment]
看了下是基于Android 5.1的，之前也有几个issue报高版本Android功能失效，我是在4.4.4上开发的。我去看下是API的变动还是因为什么问题，周末吧。
