### ISSUE TITLE
华为G660无法正常工作

### ISSUE THREAD

**Issue by Jie-OY** [geeeeeeeeek/WeChatLuckyMoney#153]
华为G660（具体参数可看下图）
情景：一开始开启插件后，都是没有问题的，可以正常实现功能。但是一旦我退出了微信的界面（不是退出微信），再点击打开，发现它出现要么没进入聊天页啥也没做，要么是进入了聊天页，但是没有自动领取红包。
PS：我在华为荣耀6和一台三星手机上都安装了，没有任何问题。唯独这个手机出现了这种情况，不知道为何？(跟他是andorid4.3有关么）
![be1e165af0837e075f337caad633bccd](https://cloud.githubusercontent.com/assets/10665384/17506965/7b408da4-5e3f-11e6-821b-28cb43b84f82.jpg)

**Comment by geeeeeeeeek** [comment]
系统版本从 Android 4.4.4 开始支持。
