### ISSUE TITLE
安卓5.1.1 smooth  与 华为3X 安卓 4.2 测试不完全成功

### ISSUE THREAD

**Issue by mengyyy** [geeeeeeeeek/WeChatLuckyMoney#16]
![mengy_20151209_230613](https://cloud.githubusercontent.com/assets/10589755/11688875/02141444-9eca-11e5-92ee-6d79dcdb4052.jpg)
插件最快10秒抢完  引入第三方小号LG K430 手动抢只需要9秒  且第二个红包触发时间远在一分钟之后
连续发红包时 后续红包无法触发插件  5.1.1上发现插件自动停止

**Comment by geeeeeeeeek** [comment]
1. 10秒才抢完感觉是你机器的性能问题了啊
2. 你确定用的是stable版本？
3. 周末会做5.1+版本适配。如果是ANR能给下系统日志吗？

**Comment by mengyyy** [comment]
10试过几次了  我的是nexus5  我姐的是荣耀3X畅玩  红包记录显示都是10秒
日志我找找

**Comment by mengyyy** [comment]
如果是ANR能给下系统日志吗？
这个日志文件在哪的…………

**Comment by geeeeeeeeek** [comment]
所以流程是这样的吗：
**你发送了两个红包，安装了插件的小号10秒后抢了第一个红包，第二个红包一分钟后才抢到。**

从来没有遇到过停止工作，所以不太明白发生了什么。如果你开发者模式里开启了显示ANR，你会看到报错，不然需要USB调试看adb log，不方便就算了。

另外，务必确认你说的是stable版本的版本？

**Comment by mengyyy** [comment]
两台手机都是stable版本  小号是lg平板没有装插件的  之前两台手机连续发红包都出现过后面发的连续的红包钱不到的情况   我是看无障碍那里发现插件停止了的  不过我姐那台就显示开启
anr我开启看看 回头有日志发给你  毕竟我这机子也不太稳定的

**Comment by mengyyy** [comment]
是发了第一个 我用小号的平板手动抢了  发现我姐抢不到后 我发了第二个 这次就没有用小号抢  然后和我姐聊天几分钟后 我姐才说插件动作抢了第二个

**Comment by geeeeeeeeek** [comment]
好的，谢谢反馈

**Comment by yiranshaxiao** [comment]
我就说为啥抢不到呢，哈哈哈哈~

```
private void checkNodeInfo() {
 ...
 mReceiveNode = node1.isEmpty() ? node1 : node0;
 ...
}
```

**Comment by geeeeeeeeek** [comment]
@yiranshaxiao 额你先不要编译，代码写了一半，这里明显写出错了。。
