### ISSUE TITLE
使用问题反馈~~~

### ISSUE THREAD

**Issue by starjason** [geeeeeeeeek/WeChatLuckyMoney#165]
1、貌似必须进入聊天窗口才能自动抢。不在聊天窗口内，不自动抢。
2、有的时候莫名的服务没有开启，所以不自动抢。或者有的时候服务明明开启的，但是并没有自动抢。
3、熄屏以后并没有自动抢。
手机为红米note3

**Comment by ray26** [comment]
请问您的系统是miui8吗，在小米4上无法复现，熄屏抢还在调试之中

**Comment by starjason** [comment]
miui 8.0.2.0 稳定版

**Comment by 3200alan** [comment]
可以发抢红包软件链接给我吗？ 谢谢

**Comment by starjason** [comment]
@ray26 还发现一个问题：
当网络切换的时候，不自动抢，服务貌似失效~
wifi切换至流量时，或者wifi断开再连上，或者流量断开再连上，都会出现无法切换，必须得都重启微信和应用。
