### ISSUE TITLE
Nexus 5X，7.0系统，无法打开插件

### ISSUE THREAD

**Issue by huagt** [geeeeeeeeek/WeChatLuckyMoney#167]
在系统设置-无障碍中没有找到'微信红包'插件。下图是无障碍服务中的服务项：

![1](https://cloud.githubusercontent.com/assets/7478224/19751882/4684932e-9c2b-11e6-8fea-3ebfc0c48e9f.png)
![2](https://cloud.githubusercontent.com/assets/7478224/19751883/468cf1d6-9c2b-11e6-99dd-257f1fbed9a4.png)
![3](https://cloud.githubusercontent.com/assets/7478224/19751884/46b0f75c-9c2b-11e6-9ee8-e4cbbac4a0fd.png)

**Comment by 3200alan** [comment]
为什么在play store里找不到软件下载？有谁可以发下载软件网址给我吗？谢谢

**Comment by ChuShouWaiGa** [comment]
出售扫雷外挂QQ2860968898

**Comment by ray26** [comment]
7.0 is in progress
