### ISSUE TITLE
抢红包BUG

### ISSUE THREAD

**Issue by fvaryu** [geeeeeeeeek/WeChatLuckyMoney#201]
如果同一个人发了两次相同的红包就无法抢了呀
`if (this.getSignature(hongbaoInfo[0], hongbaoContent, hongbaoInfo[1]).equals(this.toString())) {
                return false;
            }

            /* So far we make sure it's a valid new coming hongbao. */
            this.sender = hongbaoInfo[0];
            this.time = hongbaoInfo[1];
            this.content = hongbaoContent;
            return true;`

此处的逻辑有问题吧，时间逻辑不对吧

**Comment by laopang2** [comment]
出售微信，QQ红包扫雷外挂需要的加QQ2860968898

**Comment by li-jun** [comment]
this.time = hongbaoInfo[1];这不是还有发红包的时间判断么？
我没看过其它代码，说错了请谅解。

**Comment by ray26** [comment]
请问你这代码在哪看到的，在stable里没看到这个代码啊
