### ISSUE TITLE
一直重复打开红包

### ISSUE THREAD

**Issue by RussellPeters** [geeeeeeeeek/WeChatLuckyMoney#27]
下了最新的的release-1.2的包，打开后一直重复打开红包，微信几乎无法正常操作

**Comment by geeeeeeeeek** [comment]
3秒的最小间隔，因为没有办法很好地唯一标志红包，所以确实会重复点击。

**Comment by RussellPeters** [comment]
应该没有三秒的间隔，就一直点。我看了你的那个判断逻辑，好复杂。。也没细看，感觉如果不能准确标识的话还是上个版本策略好一些

**Comment by geeeeeeeeek** [comment]
但我测试的手机都没有出现一直点击额，能不能把有红包的界面截个图看下。

**Comment by RussellPeters** [comment]
![screenshot_20151219-121901](https://cloud.githubusercontent.com/assets/16095682/11911332/fe75a1a0-a64d-11e5-8858-8394bda60f8c.png)

**Comment by RussellPeters** [comment]
![screenshot_20151219-121901](https://cloud.githubusercontent.com/assets/16095682/11911342/687b9794-a64e-11e5-95c2-c9b8dcd96078.png)

**Comment by tandaly** [comment]
这个版本怎么一直重复弹出红包啊

**Comment by Shafley** [comment]
对，我的也是，一直重复打开红包，

**Comment by muyufan** [comment]
是啊，太bug了，下了最新版准备今天圣诞派上用场，结果一直在那儿重复点，别人发了几个我一个也没抢到，卸载去装老版本了

**Comment by geeeeeeeeek** [comment]
Bug已确认，应该把判断红包标识的代码回滚回去，但没时间改。我在Release加个说明吧，如果语言是中文的话旧版本可以用。

**Comment by geeeeeeeeek** [comment]
年底前修复。

**Comment by FreshYoung** [comment]
旧版在哪？

**Comment by FreshYoung** [comment]
时间标识可以吗？

**Comment by geeeeeeeeek** [comment]
@FreshYoung [Release](https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/tag/v1.1)。

无法获得红包到来时间。

**Comment by FreshYoung** [comment]
那怎么判断，现在是一直重复抢红包

**Comment by geeeeeeeeek** [comment]
@FreshYoung 

之前是：
```
    private String getHongbaoHash(AccessibilityNodeInfo node) {
        /* 获取红包上的文本 */
        String content;
        try {
            AccessibilityNodeInfo i = node.getParent().getChild(0);
            content = i.getText().toString();
        } catch (NullPointerException npr) {
            return null;
        }

        return content + "@" + getNodeId(node);
```

能减少点开的频率。这个版本我改错了。

**Comment by FreshYoung** [comment]
修改了这段，还是不行

**Comment by RussellPeters** [comment]
你要是需要的话我给你个能正常用的包

**Comment by FreshYoung** [comment]
可以

**Comment by RussellPeters** [comment]
[Uploading wechat.zip…]()

**Comment by RussellPeters** [comment]
[wechat.zip](https://github.com/geeeeeeeeek/WeChatLuckyMoney/files/72109/wechat.zip)

**Comment by FreshYoung** [comment]
有代码吗？我可以看看代码

**Comment by RussellPeters** [comment]
代码你直接clone下来然后看历史不就行了嘛

**Comment by FreshYoung** [comment]
en

**Comment by geeeeeeeeek** [comment]
@FreshYoung 不是给你发了[上一个Release](https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/tag/v1.1)的链接么。。可以直接下载apk，代码你去看对应commit时的仓库。

**Comment by cantonadong** [comment]
这个什么时候能修复？

**Comment by geeeeeeeeek** [comment]
@cantonadong 30号

**Comment by cantonadong** [comment]
赞，另外建议提供apk下载链接。像我这样不是程序员的能直接下载用。

谢谢。

**Comment by geeeeeeeeek** [comment]
@cantonadong 额 一直在[Release](https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/tag/v1.1)里啊，https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/tag/v1.1。

**Comment by Shafley** [comment]
不是程序员不知道release有安装包 :joy:

**Comment by geeeeeeeeek** [comment]
@Shafley 话说回来了…不是程序员你们一般用Github干什么呢…同性交友？

**Comment by FreshYoung** [comment]
哈哈哈，有可能

**Comment by charlescl** [comment]
好奇测试了一下， Android6.0.1 ， 微信最新6.3.8.56_re6b2553版本， 红包出来屏幕会闪一下，但是没有抢的动作，直到关闭服务再打开服务，然后返回微信聊天群才会正常进行抢的动作。

**Comment by geeeeeeeeek** [comment]
@charlescl 微信语言是英文吧

**Comment by charlescl** [comment]
@geeeeeeeeek 中文。从Google Play下载和从微信官网下载会有区别么，我只知道play上面没有摇一摇周边功能。

**Comment by geeeeeeeeek** [comment]
@charlescl 到时候测一下Play的版本，虽然感觉不太可能有区别。

**Comment by charlescl** [comment]
@geeeeeeeeek 你测试正常的微信版本是多少

**Comment by geeeeeeeeek** [comment]
@charlescl 

Version: 6.3.8.50_r251a77a
Update: 2015-12-9

**Comment by cantonadong** [comment]
期待新版本，新年又会有密集的红包。

**Comment by geeeeeeeeek** [comment]
@cantonadong 我年底前先把已知的bug修了。年初一(1.10)之前会有一次较大的改动，过两天放roadmap。

**Comment by Mixiaomi** [comment]
我的小米也是，我在和同事测试，一直抢不到，手机是小米4Android4.4.4，release 1.1 和1.2 都不行，debug 1.2版本也不行。

**Comment by geeeeeeeeek** [comment]
[v1.3已经发布](https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/tag/v1.3)。修复了之前红包频繁点击的bug(虽然不重复是不可能的)。另外并入了从通知栏进入抢红包的代码，下个版本启用。

[WeChatLuckyMoney开发路线图(roadmap to v2)](https://github.com/geeeeeeeeek/WeChatLuckyMoney/issues/31)也已发布，供各位参考，大版本更新，大年之一前发布。
