### ISSUE TITLE
重复id的问题

### ISSUE THREAD

**Issue by cool-delete** [geeeeeeeeek/WeChatLuckyMoney#29]
连续红包同一个id的确无法点击的 现在我自己的做法是点击完后长按删除红包 是用其他软件实现的 因为我也搞不懂辅助服务的长按代码是什么

**Comment by geeeeeeeeek** [comment]
见[Google官方文档](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo.html#ACTION_LONG_CLICK)，用`ACTION_LONG_CLICK`.

类似于这样的写法：
```
node.performAction(AccessibilityNodeInfo.ACTION_LONG_CLICK);
```

你可以自己实现下。

**Comment by cool-delete** [comment]
谢谢
