### ISSUE TITLE
id重复问题

### ISSUE THREAD

**Issue by JuneLeGency** [geeeeeeeeek/WeChatLuckyMoney#3]
估计你还没深入测试 其实发红包连续超过两页 且所有红包内容一样 基本上 id肯定会重复，这个点 hash和其他都不管用 我当时研究过，主要是listview复用的特性 ，这个问题无解的

**Comment by geeeeeeeeek** [comment]
被你发现了，确实是这样，所以说那些都是实验性的修改，试着玩的。不过现实中好像群里发红包内容不太会重复。但真要用的话还是stable那个版本，只戳最新的红包，那个我用着没问题，就是有时候界面变了之后戳过的红包会再戳一次，这个问题也是一样的，为了不错过来的红包，不过可以把阈值调高点。

**Comment by JuneLeGency** [comment]
用text 获取node 有时候 也不准 我后来 id 结合node 双重方式 不过 微信每次更新版本 都会 把id再混淆 所以 需要做个工具 手动保存id信息 
https://github.com/JuneLeGency/WechatRedEnv

**Comment by geeeeeeeeek** [comment]
看了你的代码

```java
static public  String chat_red_env_id = "com.tencent.mm:id/wm";
static public  String open_env_button_id = "com.tencent.mm:id/aww";
static public  String money_info_id = "com.tencent.mm:id/aub";
```

群聊里有多个红包时，它们的id都是上面的字符串吗？

混淆倒是一个麻烦的事情，因为你无法控制不同机器上微信的版本。思路倒是不错，我也不是搞Android的，没想到这个做法，学习了~

**Comment by geeeeeeeeek** [comment]
说的实在点，除了直接戳最新的那个红包，并没有什么靠谱的办法能把所有红包不重复、不遗漏地都戳到。

**Comment by JuneLeGency** [comment]
没办法的  我当时的思路是看能不能把时间属性搞到 加上去 但是微信的时间属性很难取 所以基本不能去重
