### ISSUE TITLE
反馈几个需求和问题

### ISSUE THREAD

**Issue by cantonadong** [geeeeeeeeek/WeChatLuckyMoney#30]
首先感谢你的插件。
我是从手机乐园下载到的，是稳定版。
使用中遇到一些问题和需求点，反馈如下：
- 反复点击红包（对于已打开过不再打开）
- 必须屏幕定位到的红包才会抢（希望可以自动抢屏幕中显示出的多个红包）
- 能自动监控红包并点击（自动进入群聊天界面抢，不用必须在某个群聊天界面内）
- 电脑端设置手机免打扰时也能抢
- 已点击过的红包，可手工点开查看详情（不会触发自动返回）

谢谢

**Comment by geeeeeeeeek** [comment]
1. 从通知自动进入微信红包可以使用[这个插件](https://github.com/lendylongli/qianghongbao)，我不会加到我自己的版本中。聊天列表自动进入可以考虑。

2. 重复点击会优化，但很难做到不重复。

3. 插件需要读屏幕，你手机息屏了就用不了了。

本身希望做的是无侵扰的插件。So, stay simple.

**Comment by muyufan** [comment]
你这个“无侵扰” 是啥意思？是不是微信无法知道是插件点的还是人手点的？

**Comment by geeeeeeeeek** [comment]
相对于其他一些插件根据通知来判断，你在群聊字打了一半跳到了别的群去，我觉得这个体验很不好，所以只做了当前群聊。

至于微信，我猜是根据API调用次数吧，悠着点就没事。

**Comment by cantonadong** [comment]
还有个小问题。
有时候插件无法自动开启 即使在聊天界面。需要手工点进去一次，才会生效。

已经在绿色守护、阻止运行里放过了。

**Comment by geeeeeeeeek** [comment]
@cantonadong 这个各种Android版本都没遇到过……

**Comment by cantonadong** [comment]
我的是CM11 M11

**Comment by spancel** [comment]
@geeeeeeeeek 息屏代码还是可以模拟点的，手机锁屏就点不了
