### ISSUE TITLE
WeChatLuckyMoney开发路线图(roadmap to v2)

### ISSUE THREAD

**Issue by geeeeeeeeek** [geeeeeeeeek/WeChatLuckyMoney#31]
**Features:**
- [x] 新增 自动更新机制
- [x] 新增 从聊天列表进入抢红包的可选项
- [x] 新增 从通知进入抢红包的可选项
- [x] 优化 判重算法
- [ ] ~~新增 红包日志~~
- [x] 新增 辅助服务的说明
- [x] 新增 春节主题界面
- [x] 更换 应用图标
- [x] 更换 包名

现在主要的bug都已经修复，新年可以愉快地抢红包了。上面的这些功能会在2016.1.20之前加入，版本号直接跳到v2，修复一些没有处理的逻辑，之后就比较稳定了。

**Comment by cantonadong** [comment]
2、3建议搞个开关，不然影响体验。
1档，群内自动抢
2档，聊天列表自动抢
3档，监控推送消息抢

**Comment by geeeeeeeeek** [comment]
@cantonadong 谢谢建议，会提供设置项的。

**Comment by charlescl** [comment]
对，其实做一个有红包就消息提示然后切换到红包的窗口已经不错了，微信一直都是设置静音。
自动抢的逻辑难度很高，而且有被封的风险。

**Comment by geeeeeeeeek** [comment]
@charlescl 好吧看错了 是某个初一

反正现在群聊红包太丧心病狂了 看到再去点完全抢不到...

**Comment by charlescl** [comment]
是的，大群10个的红包基本可以放弃。
我意思是能否设置停在红包出现的群而不去抢，半辅助形式，规避封号风险。
我平时开着主动显示，来群消息了，点两下屏幕直接抢，只是分不清来的是否红包消息，有提示的话就不用每次亮屏都瞄一眼。

**Comment by geeeeeeeeek** [comment]
@charlescl 可以考虑

**Comment by charlescl** [comment]
给个思路看有没有价值：每次成领了红包后会有个提示“你领取了***的红包”，能否对比这些提示的列表和红包发送人的昵称，剔除那些肯定已经领过的红包。 比如频率发送比较慢的时候，一个红包跟着一个领取提示，昵称对上的话，这个红包就肯定打开过，不用再去打开。
条件：打开群的昵称显示。

**Comment by biaji** [comment]
不容易。取不到红包的发送人名称。

**Comment by idctop** [comment]
有个功能需要增加啊。就是能选择哪个群不开启抢红包这功能的。屏蔽指定群吧。

**Comment by hsl313** [comment]
抢完红包的返回情况反馈!(版本1.3) #38

抢完红包之后建议返回微信主界面:
因为会定时点击最后一个!
不能聊天、点击语音会再点击最后一个红包一次!
上述情况似乎没有对已经抢完的红包进行判断！
速度不流畅!还可以快点!

**Comment by cantonadong** [comment]
其实除了判重，其他优先级都可以是负数。

**Comment by xiaohaier112** [comment]
红包被自己抢到行，在那个红包下有一行字，这个可以判断的吧

**Comment by xiaohaier112** [comment]
自己抢到红包时，红包下面会有“你领取了谁谁的红包”，主要识别红包二字，有这两个字就百分百是抢到的了

**Comment by geeeeeeeeek** [comment]
更新预告
---
这个版本的开发即将告一段落，还需要点时间测试，本周即可放出:smile:

除了红包日志、自动更新、用户界面等基础功能的完善之外，这个版本重点带来了**更自由的监视选项**。例如这些情景：

 - 怕被微信封红包功能，可以关闭监视当前聊天选项，把红包带到你面前自己打开
 - 过节时很多群同时发红包，监视聊天列表不错过每一个群
 - 监视微信的新消息提醒，锁屏了也能立刻抢到红包

不同的需求都能被满足。输入文字时暂停监视等更多优化敬请期待周末的Release~

![qq20160121-1 2x](https://cloud.githubusercontent.com/assets/7262715/12454624/52269658-bfd3-11e5-8883-c4e9ebf4a041.png)
![qq20160121-2 2x](https://cloud.githubusercontent.com/assets/7262715/12454710/a877ee1c-bfd3-11e5-8127-b6cd35841609.png)

**Comment by cantonadong** [comment]
判重最重要啊。

**Comment by geeeeeeeeek** [comment]
@cantonadong 判重应该没什么问题了

`发送者姓名` + `红包内容` + `上下文`

如果这样还重复的我也没办法了

**Comment by idctop** [comment]
赞👍！有技术实力派作风！看过你的代码，结构没改变的话，我怕会卡机。来自我的华为手机-------- 原始邮件 --------主题：Re: [WeChatLuckyMoney] WeChatLuckyMoney开发路线图(roadmap to v2) (#31)发件人：Zhongyi Tong 收件人：geeeeeeeeek/WeChatLuckyMoney 抄送：idctop 更新预告

这个版本的开发即将告一段落，还需要点时间测试，本周即可放出

除了红包日志、自动更新、用户界面等基础功能的完善之外，这个版本重点带来了更自由的监视选项。例如这些情景：


怕被微信封红包功能，可以关闭监视当前聊天选项，把红包带到你面前自己打开
过节时很多群同时发红包，监视聊天列表不错过每一个群
监视微信的新消息提醒，锁屏了也能立刻抢到红包


不同的需求都能被满足。输入文字时暂停监视等更多优化敬请期待周末的Release~

**Comment by setuer** [comment]
今天周五了，不知V2版本何时放出来？

**Comment by StearArre** [comment]
今天周六了，晚上有一大波红包来袭，不知道能不能等得到最新版，哈哈哈~~

**Comment by geeeeeeeeek** [comment]
@StearArre @setuer 已经在写Release Notes了，其实前几天就能发了，但测试的时候某个Android 6.0的机型出了一些问题，所以一直在纠结

**Comment by StearArre** [comment]
@geeeeeeeeek 坐等新版本，辛苦啦
