### ISSUE TITLE
release提供的下载不了啊

### ISSUE THREAD

**Issue by cantonadong** [geeeeeeeeek/WeChatLuckyMoney#32]
是不是被墙了

**Comment by cantonadong** [comment]
提供个国内网盘地址行么？

**Comment by geeeeeeeeek** [comment]
Github的一些文件资源托管在AWS上，刚测试了下，确实是这个原因。

我本人不会将代码和安装包放在Github之外，也不会在各应用市场上架。建议你找一个稳定的网络，或者多试几次，抱歉了。
