### ISSUE TITLE
我想基于此代码进行修改为qq版本的

### ISSUE THREAD

**Issue by flylai** [geeeeeeeeek/WeChatLuckyMoney#33]
你好，似乎更改监控的文字常量无法达成效果，请问该如何修改呢，谢谢
QQ6.1

**Comment by geeeeeeeeek** [comment]
逻辑可能不一样，以及说不定那个QQ群里的“发红包啦”是图片之类的，你自己用DDMS调试下。

**Comment by flylai** [comment]
我新建另一个程序主界面只有一个按钮， 按钮文字和你程序里的文字常量一致，打开抢红包发现不会自动点，是我手机的问题还是无法识别按钮文字呢？
谢谢

**Comment by geeeeeeeeek** [comment]
我有个xml指定了监听的包名，你是不是没改。

**Comment by flylai** [comment]
之前没改_(:з」∠)_，不过改了之后也没用...

**Comment by geeeeeeeeek** [comment]
你可以fork之后把代码传上来看…还有测试的app…不然谁知道是什么鬼…

**Comment by flylai** [comment]
已经解决，qq那边也是文字的谢谢(＾o＾)ﾉ
