### ISSUE TITLE
1.3版本问题反馈

### ISSUE THREAD

**Issue by cantonadong** [geeeeeeeeek/WeChatLuckyMoney#34]
1、对于已领过的红包，通过滚屏上移或下移，移出屏幕范围再移动回来，还是会自动再点击。
1.1、停在聊天记录里的红包界面（已领过），超时熄屏，再打开，还会自动点击。
1.2、如果红包在聊天界面的最下面（最后一条记录），不会自动触发抢红包。
2、自己主动点进去的红包，不自动返回（我想看看大家领的红包记录）
3、apk加个版本号，app界面加个版本号。

目前实战下来的结果是，每次滚屏都会重复点击。

**Comment by geeeeeeeeek** [comment]
**原理:**

1. 视图状态变化时(eg. 滚屏上下移)，检测一次视图中的内容。
2. 如果红包上的文字与缓存不一致，打开。
3. 如果红包上的文字与缓存一致，但缓存过期(5s)，打开。

没有很好的办法可以唯一标识一个红包，因此重复打开是不可避免的，我认为问题不大。Cache Expiration Time已经很大程度上改善了体验，如果只按文字匹配的话会遗漏一些红包。考虑过上下文等其他量，但会增加性能负担，需要权衡。

**Comment by zpfZPFgithub** [comment]
这种实现腾讯很难进行封杀。因为仅仅是在客户端进行（遍历节点等），但是此种方法很难进一步推进功能。比如说某宝所谓的透视红包插件

**Comment by mengyyy** [comment]
存在自己和自己的聊天窗口时会一直打开
