### ISSUE TITLE
建议在界面中增加选项，可以在此服务启用时防止锁屏

### ISSUE THREAD

**Issue by yoke88** [geeeeeeeeek/WeChatLuckyMoney#36]
有些手机由于安全原因，可能会无法关闭锁屏，但是类似播放软件之类的应用，可以让系统不锁屏，因此建议该程序加入防锁代码，同时可以降低一定程度的屏幕亮度（节电）

**Comment by geeeeeeeeek** [comment]
会考虑

**Comment by spancel** [comment]
呵呵，手机一直亮屏，太耗电了，还不如增加解锁来得直接
