### ISSUE TITLE
能否不抢个数为1的专属红包？

### ISSUE THREAD

**Issue by tedzyc** [geeeeeeeeek/WeChatLuckyMoney#39]
本来想在“开发路线图”的isuue里面跟帖，怕被淹没，所以单独开了个贴

本人最近也忙，没有时间看抢红包的代码。
群里常发给某人的专属红包，如果自动抢了的话，别人就知道你是在用作弊软件了。
本人觉得这个是个很重要的功能。希望大神们关注此软件的隐蔽性，隐蔽性是第一位的，速度不是最重要的。

另外不知在抢之前能否获取红包的金额，群里常常发1分钱的红包，以此来侦测抢红包外挂。如果可以的话，望加入：“如果红包的金额大于20元的启用最速抢，0.1元一下的无视，启动2次最速抢之后进入稍作停顿抢”的策略，回回“手气最佳”也容易暴露

**Comment by geeeeeeeeek** [comment]
你 能 告 诉 我 点 开 之 前 如 何 知 道 里 面 的 金 额 吗 … …

**Comment by tedzyc** [comment]
我估计也获取不到金额
那红包个数在点之前能获取吗, (我把抢到的专属红包都退了), 如果程序想饿狼一样不加区分的抢，迟早有一天要被踢出群的

**Comment by geeeeeeeeek** [comment]
也不行

可以考虑过滤包含特定的红包文字

**Comment by tedzyc** [comment]
那就烦请过滤“专属”二字吧

**Comment by cantonadong** [comment]
笑死我了

**Comment by wxm419** [comment]
为什么会有啥都不懂的人来GIT提issue。。。
这些人为了那几毛钱也是拼了

**Comment by cantonadong** [comment]
不要这么说吧，我们都不懂代码。并不代表我们不懂需求和场景啊。都是为了共同做好这个工具。
