### ISSUE TITLE
赞～我竟然编译测试了一下。。。

### ISSUE THREAD

**Issue by jiajunhuang** [geeeeeeeeek/WeChatLuckyMoney#4]
报一个bug， 多个红包连发的时候，程序会抢不赢，只抢到最后一个。(stable)

哈哈哈，好玩～

**Comment by geeeeeeeeek** [comment]
请看我的注释……

> "stable分支的插件只点击最新的红包，根据目前测试抢红包成功率100%"

以及我记得好像是设了10ms的间隔的，不然一直读屏会炸的，这个阈值你当然可以调了，调大了性能好但可能会错过一起来的红包，调小了就会掉帧卡顿。微信一次数据加载出来的两个红包一般是没有时间间隔的，dev分支虽说是将屏幕上的红包都遍历了一遍但是会存在这样那样的问题……

至于原因请看 #3 …相比之下只盯着最新的红包是最优的选择

**Comment by geeeeeeeeek** [comment]
这个就是写着玩的嘛，你也可以根据你的使用情景修改，比如读通知啊读消息列表啊，虽然我比较倾向于这种侵扰比较小的方式，不会说你聊天字打了一半突然跳到另一个群戳红包去了。

**Comment by jiajunhuang** [comment]
嗯～其实我测试的时候用的时pc版聊天，哈哈～
