### ISSUE TITLE
消息中带有红包文字导致的bug

### ISSUE THREAD

**Issue by cantonadong** [geeeeeeeeek/WeChatLuckyMoney#40]
今天遇到一个问题，就是有个人发了一个淘宝红包文字。就是那种淘口令的，然后跟了2条文字，都含有红包文字。
然后这3句话在当前窗口是最后3句。
然后我的手机就快速的来回退出、进入、退出、进入这个群。根本点不了。
直到下个人刷了几句话才停止。

**Comment by RussellPeters** [comment]
我也有这个问题，那天微信一个公众号发了条消息不知道匹配了哪个条件，一点开微信就来回进入退出进入退出，完全没法操作，后来关了插件，又把那条对话删了，再打开才正常

**Comment by geeeeeeeeek** [comment]
恩，马上修复。@cantonadong 能给下出错的文字吗？

**Comment by cantonadong** [comment]
已经删了，不然点不过手机。

**Comment by cantonadong** [comment]
今天又遇到了。
两个条件：
1文本含红包，如：抢红包
2在聊天界面最后一条
