### ISSUE TITLE
微信6.3.9.48_refecd3e适配

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/WeChatLuckyMoney#41]
微信最新版已经无法使用了，红包领取界面已经被改掉了

**Comment by geeeeeeeeek** [comment]
@ray26 应该不是封杀，快过年了例行升级吧，新版还挺好看的

新版的红包领取界面比之前包含了更多信息，查重更好做了

适配新版界面的版本这两天就会发出来

**Comment by geeeeeeeeek** [comment]
搞定

**Comment by ray26** [comment]
点个赞👍，效率很高

**Comment by geeeeeeeeek** [comment]
**v1.4 (2016.01.16)** 

1. 修复了微信新版(6.3.9.48_refecd3e)红包UI调整导致的功能失效。Fix failure caused by new WeChat Hongbao UI. Related issue #41.

**Release 地址：**
https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/tag/v1.4

**Comment by JackyTianer** [comment]
似乎升级到1.4版本后，无法从外部唤起进入聊天页面， 测试机 小米4  系统版本 miui 5.12.11 android 4.4.4, 微信版本 6.3.9.48_refecd3e

**Comment by JackyTianer** [comment]
@geeeeeeeeek  似乎升级到1.4版本后，无法从外部唤起进入聊天页面， 测试机 小米4  系统版本 miui 5.12.11 android 4.4.4, 微信版本 6.3.9.48_refecd3e

**Comment by geeeeeeeeek** [comment]
@JackyTianer 你是指注释的那段代码？

**Comment by leonis999** [comment]
请问1.4是不是不支持后台抢红包了？以前1.3可以的。

**Comment by geeeeeeeeek** [comment]
@leonis999 不是很明白，后台抢红包是指监听信息推送吗？1.3中没有这个功能吧

**Comment by JackyTianer** [comment]
@geeeeeeeeek 1.3版本时候，当你在读微博，逛知乎时 ，如果收到微信红包消息，会自动进入微信点击红包，在1.4的时候这个功能消失了。

**Comment by ray26** [comment]
@JackyTianer 升级2.1.1版本

**Comment by geeeeeeeeek** [comment]
@JackyTianer我确信这个功能在1.3是没有的..你升级到最新的2.0.1吧 最新版可以监视通知的

**Comment by JackyTianer** [comment]
好的， 已升级测试通过。
