### ISSUE TITLE
微信升级后探测到该APP，然后直接不让用了

### ISSUE THREAD

**Issue by turner1015** [geeeeeeeeek/WeChatLuckyMoney#42]
昨天微信升级之后，提示不让用抢红包软件，然后直接封3天不让抢红包，哎。。。。这下完了..... T T

**Comment by geeeeeeeeek** [comment]
@turner1015 珍稀物种…为什么整天测试的我就遇不到呢

能不能详细说明一下你在被封之前做了什么？疯狂地抢了一堆红包，还是突然就弹了出来？当时这个插件是否在后台运行？

还有这个提示具体是怎样的？能否说明下？谢谢。

**Comment by turner1015** [comment]
前两天倒是不停的抢了一堆红包，但是那时也没啥问题。昨天微信升级后刚一点红包，就弹出一个提示，不能使用抢红包辅助软件，3天内暂时停止使用抢红包功能。大概就这个意思。

**Comment by geeeeeeeeek** [comment]
我用的也是这个版本。原因无法确定。

Duplicate of #19.
