### ISSUE TITLE
三星Note5 6.3.9.48版本微信，使用1.4版本bug

### ISSUE THREAD

**Issue by hugestar** [geeeeeeeeek/WeChatLuckyMoney#44]
在开启红包插件后，只要进入微信就会显示微信红包已停止
返回插件界面，可以点击开启插件，但是辅助功能里已经开启
ps.不知道是否跟昨天被封禁止抢红包3天有关？

**Comment by RussellPeters** [comment]
你这个就是那个数组越界的问题

**Comment by hugestar** [comment]
有方法解决吗？是插件问题吗？

**Comment by ray26** [comment]
等更新吧，在 #43

**Comment by turner1015** [comment]
你也被禁止3天？是不是一点红包就出现【不能使用辅助软件。。。】那个对话框啊？

**Comment by ray26** [comment]
没有，应该是你用的太频繁了，微信后台检测到异常就封掉了

**Comment by ray26** [comment]
理论上和app是没关系的（ps：装了xxx管家除外）

**Comment by turner1015** [comment]
那咋办，怎么才能解封啊，各位大神，有没有什么好的办法？

**Comment by ray26** [comment]
等吧，或者你发邮件给腾讯求个情

**Comment by turner1015** [comment]
求个球啊求，这跟流氓谈条件没啥区别，大不了这个号不要了！

**Comment by ray26** [comment]
三天，大不了三天不发红包，就当拿个教训

**Comment by turner1015** [comment]
问题是早已经过了三天，还不解封。。直接判了死刑！

**Comment by ray26** [comment]
截图看看怎么说的，理论上不会不守信用啊

**Comment by turner1015** [comment]
这里咋发截图啊？

**Comment by ray26** [comment]
文本框下面有个selecting them就是上传文件的

**Comment by turner1015** [comment]
![1049341555](https://cloud.githubusercontent.com/assets/3008552/12371979/823b7282-bc81-11e5-9c8d-7564b6ec16c8.jpg)

**Comment by turner1015** [comment]
换SS，能上传了。。

**Comment by turner1015** [comment]
总是出现这个对话框，真是醉了。。。这腾讯真特么让人蛋疼啊！

**Comment by hugestar** [comment]
我之前是用了另一个软件，结果被封的。现在才1天，所以我想知道的是数组越界是和被封有关系吗？还是这个版本的插件问题。

**Comment by ray26** [comment]
数组越界是app本身的问题，和被封没问题，被封的唯一可能就是用的太频繁了，后台检测到异常就封了

**Comment by hugestar** [comment]
哦，那就明白了。等着更新和解封 = =

**Comment by turner1015** [comment]
我估计年前是不能给我解封了。。

**Comment by geeeeeeeeek** [comment]
李狗嗨看了一半……

@RussellPeters @ray26 @turner1015 请帮忙测试 #43 中的数组越界问题是否解决？我发现新版红包不只变了UI，逻辑也有些改动，后面再看了，问题不大

https://github.com/geeeeeeeeek/WeChatLuckyMoney/releases/download/v1.4/WeChatLuckyMoney-v1.4.apk
