### ISSUE TITLE
通知监视问题

### ISSUE THREAD

**Issue by ray26** [geeeeeeeeek/WeChatLuckyMoney#45]
建议尽快加入通知监视进入抢红包的服务，要不然点进去再抢的速度根本跟不上，有插件和没插件基本上一个样😘

**Comment by geeeeeeeeek** [comment]
@ray26 别急嘛，你把代码里的注释去掉就有通知监视了~ 我是想和大版本一起放出来的

**Comment by ray26** [comment]
我尝试了，只去掉注释在我的系统里是不起作用的

**Comment by W-quan** [comment]
其实最大的问题是开启了插件后打字就要崩溃了

**Comment by geeeeeeeeek** [comment]
@W-quan 会提供开关

 - 只监听通知
 - 只监听当前聊天
 - 同时监听

**Comment by W-quan** [comment]
@geeeeeeeeek 不知道什么时候能放大招呢？   其实应该在打字的时候临时关掉监听

**Comment by geeeeeeeeek** [comment]
@W-quan 正在写

**Comment by W-quan** [comment]
@geeeeeeeeek 支持你。基于xposed的有一个叫luckmoney的模块。但是作者没有公开代码。 不太敢用。听说可以在手机休眠的时候也能抢到。

**Comment by yiranshaxiao** [comment]
@W-quan 待我去反编译他的
