### ISSUE TITLE
图片不能识别了

### ISSUE THREAD

**Issue by a449122580** [geeeeeeeeek/WeChatLuckyMoney#47]
腾讯换拆包的图片了，只能弹出不能自动拆

**Comment by geeeeeeeeek** [comment]
@a449122580 更新啊 1.4就是修复这个问题的

**Comment by a449122580** [comment]
就是更新后也一样不能点開这个字，需要手动，源码包里这个路径的图片还没替换 WeChatLuckyMoney-1.4.zip\WeChatLuckyMoney-1.4\app\src\main\res\mipmap-xxhdpi\ic_launcher.png

**Comment by a449122580** [comment]
![ic_launcher](https://cloud.githubusercontent.com/assets/13272715/12479338/6d432f58-c075-11e5-89c9-0b960a56a58c.png)

**Comment by geeeeeeeeek** [comment]
@a449122580 ic_launcher是应用图标，和这个没关系

是检测到Button点击，不再是文字了，不是很清楚为什么你打不开

**Comment by ray26** [comment]
你是不是后台服务没开，ic_laughter是图标，和这个没关系
