### ISSUE TITLE
腾讯对这类自动抢红包的软件有封杀，提醒各位注意

### ISSUE THREAD

**Issue by HorseLuke** [geeeeeeeeek/WeChatLuckyMoney#5]
包括腾讯手机管家、和部分和腾讯合作植入相关SDK的手机厂商，会将release上编译好的apk报病毒。

但明明这apk都没发送短消息这权限好不2333333333

（和腾讯合作植入相关SDK的手机厂商）

![676781252947903632](https://cloud.githubusercontent.com/assets/1235046/11566798/f52a53ba-9a1e-11e5-90b8-f77a12a8055c.jpg)

![270804143527889663](https://cloud.githubusercontent.com/assets/1235046/11566810/ffc86348-9a1e-11e5-9208-a2af37daa4ca.jpg)

（腾讯手机管家）

![363459624038738054](https://cloud.githubusercontent.com/assets/1235046/11566717/961d3d7e-9a1e-11e5-85b4-8f467e0eff13.jpg)

**Comment by geeeeeeeeek** [comment]
感谢提醒。

腾讯实在是太无耻了。。能不要编造借口么。。就是不知道它是根据什么特征分析的，微信的包名+AccessibilityService？如果分拆一下不知道能不能绕过。

不过也提醒大家，**根据版权约定，这个项目只能用于教学目的，请在可控范围内使用编译出的应用**。

**Comment by biaji** [comment]
换个包名应该就ok

**Comment by ihciah** [comment]
求越狱后的IOS版

**Comment by geeeeeeeeek** [comment]
@ihciah 拿新版的选课助手来换？（逃

其实代码根本不通用…

**Comment by spancel** [comment]
这种号称安全软件的，可直接干掉

**Comment by ihciah** [comment]
@geeeeeeeeek 2333333333目测二轮后一周内就会有人写出刷课机
话说要不要分析下协议,全自动抢红包=_=

**Comment by geeeeeeeeek** [comment]
@ihciah 你说的这种就需要XPosed了，hook到它的方法，这样动静太大了。。

**Comment by ihciah** [comment]
@geeeeeeeeek 纯脚本模拟登陆、抢红包((*′ ▽‘)爻(′▽‘*))

**Comment by turner1015** [comment]
原来如此，果然是手机的问题，换小米！
