### ISSUE TITLE
1.2版本以来的一个自动点击bug

### ISSUE THREAD

**Issue by cantonadong** [geeeeeeeeek/WeChatLuckyMoney#53]
就是某些场景下，会自动点击“是否打开系统定位”的弹窗。

**Comment by cantonadong** [comment]
![Uploading WeChat_1453689331.jpeg…]()
![Uploading WeChat_1453689457.png…]()

**Comment by cantonadong** [comment]
发不上图，作者验证一下吧。

**Comment by geeeeeeeeek** [comment]
没有明白，是否打开系统定位 的弹窗是什么..没图无法理解

那个[Uploading image.png…]()是因为图片还没上传完，完成之后就变成图片链接了

**Comment by charlescl** [comment]
他说的系统定位弹窗是指某些要获取用户位置的公众号，弹出来一个请求位置的提示。

**Comment by brucevanfdm** [comment]
聊天中，给对方发出红包（红包数量1，非群聊），反复读取

**Comment by cantonadong** [comment]
1、公共号等服务申请获取地理位置时，会自动点击是，并跳转到开启gps服务页面。
2、朋友圈点击删除自己发布消息时，会自动点击确认，然后删除。

**Comment by geeeeeeeeek** [comment]
Fixed in PR #79.
