### ISSUE TITLE
我想请问下你监听通知的逻辑

### ISSUE THREAD

**Issue by mrzoudanwei** [geeeeeeeeek/WeChatLuckyMoney#57]
我之前用监听写感觉多开个服务不方便，你的没有用监听写通知栏，是怎么读取通知信息的

**Comment by geeeeeeeeek** [comment]
`AccessibilityService` : `AccessibilityEvent.TYPE_NOTIFICATION_STATE_CHANGED`

**Comment by mrzoudanwei** [comment]
首先 谢谢你回答，我刚刚按照你的代码设置加到我的demo中去，但是却没有自动点击，我点击之后能抢，这什么原因0.0

**Comment by geeeeeeeeek** [comment]
没看到你的demo代码怎么知道…

比如…你AccessibilityService的config里面是否有把Notification加入监听的类型？

**Comment by mrzoudanwei** [comment]
再打扰一下你，你更新的项目，是不是运行起来有bug，抢不到红包的呀..

**Comment by geeeeeeeeek** [comment]
你说清楚啊

**Comment by mrzoudanwei** [comment]
怎么说呢，我用你的apk抢不成功，自已弄以一个一样的demo 也是监听不到通知，要么就是进去不点

**Comment by mrzoudanwei** [comment]
haiyou还有你代码版本比apk版本小一个版本啊

**Comment by ray26** [comment]
@mrzoudanwei 代码版本和apk版本是同步的，不存在小一个版本的问题

**Comment by mrzoudanwei** [comment]
@ray26 那你有没有遇到这种情况，access那个服务开了，可是点玩一个后回到app发现提示未开服务，微信红包夜店不了，设置里面服务是勾上的，必须重新点一次才能再抢红包

**Comment by ray26** [comment]
@mrzoudanwei 无法复现，没有这种情况

**Comment by geeeeeeeeek** [comment]
@ray26 他说的是首屏那个“开启插件”的字不会变，这个我已经fix了，下次release一起发

**Comment by ray26** [comment]
get√

**Comment by mrzoudanwei** [comment]
@geeeeeeeeek  可以我讲错了，我自己实现了检查服务是否开启，发现抢完一次以后再抢就没有自动点击的效果，回app看提示未开启服务，但是跳到设置界面却已经开了，我搞了一上午，没清楚哪里错了，之前运行都没问题的

**Comment by ray26** [comment]
@mrzoudanwei 你可以参考milestone/v2.0里面对于服务状态检查的实现，你可能改出问题了

**Comment by mrzoudanwei** [comment]
@ray26 郁闷了，我重建一个工程一模一样的代码，后面的就不报错0.0
