### ISSUE TITLE
微信红包 2.1 更新预告

### ISSUE THREAD

**Issue by geeeeeeeeek** [geeeeeeeeek/WeChatLuckyMoney#61]
- [x] 优化 仅在WiFi环境下自动检测更新
 - [x] 修复 插件开启后按钮仍然显示“开启插件”
 - [x] 新增 屏蔽指定红包文字的可选项
 - [x] 新增 拆开自己发的红包的可选项
 - [x] 新增 (息屏抢红包)保持系统唤醒状态的可选项
 - [ ] 新增 反反外挂策略

预计发布时间：2016.01.30，可以在应用内直接更新

**Comment by jp1017** [comment]
good job

**Comment by cantonadong** [comment]
建议包名别跟红包沾边。

**Comment by HKOYES** [comment]
有测试过瓦力自动抢红包，很容易封
但是我用提醒软件手动加一键抢没有被封，只是微信更新一键抢红包就失效了。
希望可以过滤关键字！
2.0抢过的包再进群还是会点一次.有时候会暂停运行

**Comment by geeeeeeeeek** [comment]
过滤关键字 比如呢？

**Comment by HKOYES** [comment]
可以添加关键字，比如 私 专 退 还 等字样红包

**Comment by HKOYES** [comment]
之前使用猎豹安全大师抢红包提醒功能配合1.4版可以完成自动抢红包，不封号，目前使用2.0已经可以全自动使用到现在没有封号速度很快，
就是不想抢的红包有时候也会抢，别人专属私包不能抢，抢了还要翻倍退回，这样屏蔽一个群就还是有很多红包就不能抢了。
重复进群还是会点第二次已经抢过的，
监控群内聊天红包是否可以改多选呢。
在群里自己点一次就可以拉。

**Comment by HKOYES** [comment]
挺好用的，完善一定更好，辛苦了，感谢

**Comment by HKOYES** [comment]
比如只监听最新红包自动抢，会不会避免点击已经点过或者已经屏蔽过的就不会在点。

**Comment by geeeeeeeeek** [comment]
@HKOYES 好

**Comment by caijiamx** [comment]
建议新增打赏功能，你懂的。

**Comment by xiaohaier112** [comment]
有没有人发红包界面一直按数字2的，我的会一直按2键，用百度输入法

**Comment by xiaohaier112** [comment]
关掉软件就不会按了，应该是软件识别有点问题！麻烦看一下！手机是三星G3509I电信版的

**Comment by ray26** [comment]
@xiaohaier112 无法复现，能不能提供调试信息

**Comment by xiaohaier112** [comment]
我不会提取调试信息啊

**Comment by zhouyl** [comment]
@caijiamx 打赏这种东西还是不要随意搞的比较好。。但开源项目在 github 上搞个 Donate 还是可以的，自由捐赠，不存在赢利为目的，也就不会触碰敏感地带。 如果有的话我会支持，以鼓励这种开源精神

**Comment by HKOYES** [comment]
这个发红包自动按键的问题我也有，
我2台华为4X  但是电信版不会按，移动版就会按，红米Note2也不会按，
应该是安卓或者手机版本问题吗？

**Comment by geeeeeeeeek** [comment]
@ray26 有空的话能帮我测试下`release/2.1`分支下的wakelock行吗？在MIUI下表现不合预期，屏幕不会dim，但一段时间(Sleep的时长)后直接息屏。我怎么都看不出代码有什么问题，你看看其他机型也有问题吗？

主要的代码：
https://github.com/geeeeeeeeek/WeChatLuckyMoney/blob/release/2.1/app/src/main/java/xyz/monkeytong/hongbao/utils/PowerUtil.java

**Comment by ray26** [comment]
@geeeeeeeeek 好的，晚上我跑一下

**Comment by ray26** [comment]
@geeeeeeeeek 已经定位理问题，休眠时间好像不是系统apk不能修改，你只能在应用内亮屏，一出来就会灭，修改休眠时间的属性，做个开关控制，但是6.0权限控制好像就不能用。或者自己抓一个wake lock不释放，抓一个亮屏的wakelock

**Comment by ray26** [comment]
晚点我试一下，发个pr

**Comment by geeeeeeeeek** [comment]
@ray26 似乎和我测试的不太一样，不管在不在应用内，在Activity内还是在Service，都会有一样的问题。至少在Sleep的时长之前屏幕没有dim，所以我觉得问题在于WakeLock没有阻止Sleep。

你在Flyme机器上的测试如何？代码并入release/2.1吧，stable在发布前先不动了。

**Comment by ray26** [comment]
@geeeeeeeeek 我刚刚在tos上也测试了一下，你讲的情况也出现了，所以我建议先打个tag，再并入分支，以后出现了大问题再注释了就可以

**Comment by ray26** [comment]
@geeeeeeeeek 晚点我和miui的功耗工程师谈一下怎么解决

**Comment by geeeeeeeeek** [comment]
@ray26 好，等我把剩下的代码写完。

**Comment by kinbr** [comment]
2.1版本还没发布吗？2.0更新不了﹍

**Comment by geeeeeeeeek** [comment]
@kinbr 正在测试…几个小时之内应该就发布了… 2.0更新不了是什么意思？

**Comment by zongxiaomi** [comment]
activity 的启动方式是否要改一下

**Comment by geeeeeeeeek** [comment]
@ zongxiaomi 怎么说

**Comment by zongxiaomi** [comment]
用标准的启动模式，mainactivity、SettingActivity和辅助设置页面之间回退的时候会来回反复跳转，只保留一个task即可

**Comment by geeeeeeeeek** [comment]
@ray26 release分支可以测试了，我去准备下release notes，没问题了就马上发布。

**Comment by ray26** [comment]
@geeeeeeeeek 我现在测试一下

**Comment by geeeeeeeeek** [comment]
@zongxiaomi 谢谢建议，加入下一个release。

**Comment by rootphantomer** [comment]
太帅了~赞赞赞
