### ISSUE TITLE
小米NOTE（Android6.0）开启抢红包功能后 抢红包的service直接挂掉，提示在service里的checknode出现空指针

### ISSUE THREAD

**Issue by shinyvince** [geeeeeeeeek/WeChatLuckyMoney#66]

**Comment by geeeeeeeeek** [comment]
麻烦附一下完整的log可以吗？Service挂掉的时候会有一个弹窗，点击View Summary，截屏或者发一下文字。

另外，Android 6.0的MIUI不是因为bug停止推送了么，我一直收不到更新。

**Comment by ray26** [comment]
@geeeeeeeeek 我的miui6.0体验版天天都在更新，没有挂掉的情况

**Comment by geeeeeeeeek** [comment]
@ray26 我的是开发版，不是体验版。之前22号放出来之后很多用户反馈bug然后紧急停止了推送。我还在等更新。

**Comment by ray26** [comment]
@geeeeeeeeek 体验版抢红包没问题

**Comment by yeshiyuan00** [comment]
@geeeeeeeeek  我的也是开发版，这周已经更新两次了

**Comment by yeshiyuan00** [comment]
MIUI Android 6.0报错如下
![screenshot_2016-01-29-10-41-13_com miui bugreport](https://cloud.githubusercontent.com/assets/8528966/12665835/b4dcfd84-c675-11e5-89eb-0672015629ba.png)

**Comment by geeeeeeeeek** [comment]
Fixed in my local commit. Will push later.
