### ISSUE TITLE
自己建工程，拷贝代码后无效

### ISSUE THREAD

**Issue by alphater** [geeeeeeeeek/WeChatLuckyMoney#68]
自己想测试下功能，重新建了个工程，然后拷贝相应代码，并改了包名，能成功编译，但是不能执行相应操作，比如自动抢红包，感觉所有功能都失效了。

**Comment by geeeeeeeeek** [comment]
这你自己debug啊，显然是你拷贝的时候出了问题

**Comment by alphater** [comment]
然后我检查了，没问题，我把微信进程结束后再次启动，就可以进行了，但是感觉不灵敏，有时候就会突然失效，需要结束微信进程，再次重新启动才行

**Comment by ray26** [comment]
你的代码是哪个分支的

**Comment by ray26** [comment]
是最新的吗
