### ISSUE TITLE
nexus6p 发红包输入密码框出现时 程序崩溃  无法抢红包

### ISSUE THREAD

**Issue by JerryLees** [geeeeeeeeek/WeChatLuckyMoney#69]
如题  同样的问题出现在小米手机6.0系统上

**Comment by chenshuiyin** [comment]
华为荣耀6，安卓4.4.2系统，点击服务，微信红包无反应，也就是不能正常打开服务

**Comment by niray** [comment]
把Error日志贴上好.好说话..

**Comment by ray26** [comment]
会不会提取调试信息

**Comment by JerryLees** [comment]
![111](https://cloud.githubusercontent.com/assets/6364966/12664336/af0610dc-c669-11e5-875b-e5cfd79791c9.png)
错误信息

**Comment by niray** [comment]
162 @Override
163 public void onInterrupt() {
164
165}
你是不是自己改代码了.. 163行不应该是这个

**Comment by JerryLees** [comment]
并没有 我这边手机直接从这里下载的版本 代码我并没有修改过

**Comment by niray** [comment]
`if (node2 != null && node2.getClassName().equals("android.widget.Button")) {`
莫非是这句话出问题了..

**Comment by JerryLees** [comment]
所以希望大神们看看喽

**Comment by JerryLees** [comment]
@geeeeeeeeek @ray26 @niray 发红包输入密码框出现时 程序崩溃 之后无法自动抢红包

**Comment by ray26** [comment]
Please see #66 it will be fixed later
