### ISSUE TITLE
CM12抢红包失败

### ISSUE THREAD

**Issue by isRaining** [geeeeeeeeek/WeChatLuckyMoney#7]
我的操作步骤：
1、发一块的，自动抢
2、紧接着发了1毛，自动抢
3、再发一毛，自动抢
4、再发了五块，不行了，遍历了之前的红包，五块这个没抢
5、再发一块，一直只遍历五块的那个已经拆开的红包
6、再发，还是只拆五块的红包

此时屏幕内没有文字，都是红包，起码有四五个红包在一个屏幕吧。
安卓手机是小米3的

**Comment by w4lle** [comment]
你用的stable分支？

**Comment by geeeeeeeeek** [comment]
同上，如果想用的话请选择stable分支的release，虽然默认只抢最后一个红包，但是比较稳定，不会出问题。dev分支原先是想尝试抢所有红包的，但技术上或多或少存在问题(参考#3 )，文档主要记录的是实践过程。

你的问题我有空去复现下，但修复的概率不大。

**Comment by onexuan** [comment]
我也测试过了，都失败的，CM12的，还有看了代码，流程还得优化一下！

**Comment by geeeeeeeeek** [comment]
@onexuan 你是说不能遍历屏幕上所有红包还是不能点开最新的红包？

**Comment by geeeeeeeeek** [comment]
以及流程什么会重构的。之前是当成一个教学案例来写的，自己班上用，测试也不充分，请见谅。

**Comment by onexuan** [comment]
stable也是不稳定版本，在我手机上全部失败，问题重现是：别人发出来红包（人对人发红包），界面进入拆红包后，界面立即退出，无法点击“拆红包”。

**Comment by geeeeeeeeek** [comment]
好，有空看下，虽然我从来没有遇到过。。
