### ISSUE TITLE
通知监听在安卓4.4以上无效

### ISSUE THREAD

**Issue by 2767321434** [geeeeeeeeek/WeChatLuckyMoney#70]
安卓4.4以上需要给读取通知权限，需要注册通知监听服务才能监听通知内容

**Comment by geeeeeeeeek** [comment]
你可以看我实现。我在4.4.4(MI Note)和6.0(Nexus 6P)上都测试通过。不知道你具体是什么情况。

**Comment by 2767321434** [comment]
miui7 。5.0.2无法监听通知，可能是miui限制多吧，加了通知监听服务，我还没测试能不能正常使用了

**Comment by 2767321434** [comment]
刚发现通知能正常监听到，可进去红包多了就傻了，要不不抢，要不就只抢最后一个

**Comment by geeeeeeeeek** [comment]
正常的行为就是`只抢最后一个`，这是有原因的，有兴趣可以翻一翻dev分支的文档，记载了当年想遍历屏幕上所有红包时遇到的各种坑，最后还是放弃了。

**Comment by 2767321434** [comment]
好吧，我也突然想到了，如果全部抢会一直循环可能没完了，添加抢过的列表也很麻烦
