### ISSUE TITLE
在部分4.1、4.3等老系统上，存在漏抢红包

### ISSUE THREAD

**Issue by cddjr** [geeeeeeeeek/WeChatLuckyMoney#72]
通过研究发现，在处于聊天界面时，findText(“领取红包”)是可以得到正确的红包数量，但是通过这些红包node去获得红包祝福语却有可能并不是最新红包的，这可能会造成红包签名一致，而忽略去点击。

比如聊天界面内已有如下红包，并且都已经抢了
恭喜发财B
恭喜发财C

然后对方又发了一个红包叫恭喜发财D，结果有可能是如下这样
恭喜发财B
恭喜发财C
恭喜发财C

或者是这样
恭喜发财A  <==在屏幕可视范围以外的更早前收到的红包
恭喜发财B
恭喜发财C

但其实最后得到的那个疑似抢过的node就是指向最新的，只要ACTION_CLICK就能点开最新的红包

除非我们切换一下微信界面(相当于重新刷新界面了)，才能得到如下正确的红包内容
恭喜发财B
恭喜发财C
恭喜发财D

这种问题在5.1.1的机子上暂时没复现出来(小米note顶配、魅族pro5)
在5.0的华为P8也没有复现，但是在三星5.0的S6复现了(几率不大)
三星4.3、联想4.1机子上高概率复现

**Comment by geeeeeeeeek** [comment]
忘了说，微信红包支持最低的版本为Android 4.4 (API level 19)。

至于三星这个坑货，我没有机子调试，但至少一半以上的issue都是发生在三星机型上面。
