### ISSUE TITLE
setAccessibilityDelegate 的问题

### ISSUE THREAD

**Issue by niray** [geeeeeeeeek/WeChatLuckyMoney#73]
如果[打开] 这个按钮添加了 setAccessibilityDelegate (自己重写了AccessibilityNodeProvider) 方法.还有其他的方法来执行OnClick操作么.?

**Comment by geeeeeeeeek** [comment]
之前没听说过这种用法，翻了下文档。个人看法，`AccessibilityDelegate`可以在调用父类方法前拓展一些操作，包括拦截。`performAccessibilityAction`就可以拦截点击操作，我不知道`MotionEvent`来模拟点击是否可以，因为`onGenericMotion`似乎也是可以重写的。

不如你做个实验？

>在应用程序中，辅助功能事件是用户与可视界面组件交互的消息。这些消息是由辅助功能服务处理。辅助功能服务使用在这些事件中的信息产生附加的反馈和提示。Android 4.0(API级别14)和更高版本上，比Android 1.6(API级别4)中介绍的AccessibilityEventSource界面，辅助功能事件已经扩展，可以提供更详细的信息。扩展后的辅助功能方法属于View类的一部分，也是View.AccessibilityDelegate的一部分。方法如下:
**sendAccessibilityEvent()**
(API级别4)当用户在一个视图操作时调用此方法。事件是按照用户操作类型分类,如TYPE_VIEW_CLICKED。你通常不需要实现该方法,除非你是创建一个自定义视图。
**sendAccessibilityEventUnchecked()**
(API级别4)当调用代码需要直接控制检查辅助功能设备的启用时，调用该方法。(AccessibilityManager.isEnabled())。如果你实现这个方法,不管实际的系统设置，执行调用时，必须假设辅助功能是启用的。一个自定义的视图，通常不需要实现该方法的。
**dispatchPopulateAccessibilityEvent()**
(API级别4)当你的自定义视图生成一个辅助功能的事件时，系统调用这个方法。在API级别14,为当前视图，默认调用该方法的实现onPopulateAccessibilityEvent(),然后为当前视图的的子视图调用dispatchPopulateAccessibilityEvent()。在Android 4.0之前(API级别14)，为了支持辅助功能服务，在自定义视图中，必须重写此方法和用描述性文本填充getText(),这就是所说的辅助功能服务,如TalkBack。
**onPopulateAccessibilityEvent()**
(API级别14)这个方法在你的视图中设置AccessibilityEvent接口中的语音提示文本。如果当前视图是产生辅助功能事件视图的子视图，也要调用该方法。
注意:在当前方法的文本上修改附加属性，可能覆盖属性设置的其他方法。虽然您可以修改辅助功能事件方法中的属性，您应该限制这些对文本内容的修改,并使用onInitializeAccessibilityEvent()方法来修改其它事件的属性。
注意:如果这一事件的实现方法完全重写了输出文本，并且这些文本不允许布局中其它部分修改其内容，这时不必在代码中调用父类的方法的实现。
**onInitializeAccessibilityEvent()**
(API级别14)系统调用这个方法在当前文本中，获取视图的状态信息。
如果自定义视图在TextView或Button上提供了交互式控制,你应该重写此方法，并需要在这个事件中设置你的视图的状态信息。这些状态信息如密码字段类型,复选框类型或
,提供用户交互或反馈的状态信息。如果你做重写这个方法,您必须调用它父类的实现,然后只修改在超类中没有设置的属性。
**onInitializeAccessibilityNodeInfo()**
(API级别14)这种方法提供了视图状态信息辅助功能服务。默认视图实现一组标准的视图属性，但如果您的自定义视图在TextView或Button提供了交互式控制服务,您应该重写此方法，并且通过该方法在AccessibilityNodeInfo对象中设置你试图的额外的信息。
**onRequestSendAccessibilityEvent()**
(API级别14)当你视图中的子视图产生了一个AccessibilityEvent，系统调用这个方法。这个步骤允许父视图修改辅助功能的事件和其他信息。如果你的自定义视图有子视图,如果父视图可以对辅助功能服务有用的事件提供上下文信息，此时，必须实现该方法。
为了支持自定义的视图的这些辅助功能方法，应该采取以下方法:
如果你的应用程序是Android 4.0(API级别14)以上，直接在自定义视图类中覆盖并实现上面列出的辅助功能方法。
如果自定义视图为兼容安卓1.6(API 4级)及以上,对你的项目中加上Android Support Library，版本5或更高。然后,在您的自定义视图类,调用ViewCompat.setAccessibilityDelegate()方法来实现上面的辅助功能方法。 对于这种方法的一个示例,请参阅Android支持库(修订5或更高)示例。
在这两种情况下,你应该在自定义视图类中实现以下辅助功能方法:
dispatchPopulateAccessibilityEvent()
onPopulateAccessibilityEvent()
onInitializeAccessibilityEvent()
onInitializeAccessibilityNodeInfo()
关于这些方法更多的实施信息,请参阅填充辅助功能事件一节。

**Comment by niray** [comment]
可是MotionEvent 的操作对象是个View.在AccessibilityNode里拿不到任何View对象..

**Comment by geeeeeeeeek** [comment]
我的意思是微信是可以拦截这种模拟点击的……如果微信设置了`AccessibilityDelegate `，`public boolean performAccessibilityAction (View host, int action, Bundle args)`就可以获取View对象。

`AccessibilityNodeInfo`中`public static AccessibilityNodeInfo obtain (View source)`好像也是可以获取到View对象的。不过我都没有试过，不敢说的太绝对。

**Comment by niray** [comment]
如果使用MotionEvent成功的话. MotionEvent中的DeviceId 是否可以伪造.因为我尝试通过
 [adb shell input tap x y ] 
来模拟点击事件,发现DeviceId为0.

**Comment by niray** [comment]
是的,我昨天试着模仿你的代码来给另外一个APP写插件,发现他对[打开] 按钮做了 处理..导致无法实现模拟打开

**Comment by geeeeeeeeek** [comment]
你试下是否可以用MotionEvent解决你的问题吧。感觉微信挺有可能会做类似的拦截，可以杀死一票用AccessibilityService的插件，得准备Plan B。

**Comment by niray** [comment]
用MotionEvent没有任何思路啊..因为木有一个View target.

**Comment by niray** [comment]
@geeeeeeeeek  有没有任何关于MotionEvent的思路..

**Comment by geeeeeeeeek** [comment]
@niray 我有空试试吧 还有别的项目在做。

**Comment by geeeeeeeeek** [comment]
@niray 确实获取不到view :-

**Comment by niray** [comment]
新年快乐：）

**Comment by geeeeeeeeek** [comment]
@niray 新年快乐！除夕还来同性交友啊2333
