### ISSUE TITLE
在聊天界面不会自动抢

### ISSUE THREAD

**Issue by act262** [geeeeeeeeek/WeChatLuckyMoney#80]
设置中已经打开了监视当前聊天页面,如果在聊天界面不会去识别红包,只能在外面识别打开

**Comment by ray26** [comment]
最新版本吗，有调试信息吗

**Comment by act262** [comment]
貌似有时候会抢，有时候不会
2016年1月29日 11:55，"ray" <notifications@github.com>写道：

**Comment by geeeeeeeeek** [comment]
@act262 Fixed.
