### ISSUE TITLE
Android 5.1.1 updateServiceStatus() func Incident Response

### ISSUE THREAD

**Issue by sendya** [geeeeeeeeek/WeChatLuckyMoney#86]
在 5.1.1环境上 点击开启 插件，进入 无障碍 设置启用后，返回 微信红包 程序
Button switchPlugin 的 Text 没改变

环境：
OnePlus 2 A2001
OxygenOS 2.1.2
Android 5.1.1
另将手机切换到 CM13 , Android 6.0.1 也是一样情况。
不知是不是只是在我手机有这个问题

**Comment by ray26** [comment]
最新的2.0.1版本已经fix了这个问题，你检查一下是不是最新的

**Comment by sendya** [comment]
是最新的2.0.1， 检查版本也是提示最新。

**Comment by geeeeeeeeek** [comment]
@ray26 已经在主代码库里了，今晚或者明天会发一个release一起更新。

**Comment by sendya** [comment]
@ray26 @geeeeeeeeek  ok, 谢谢
