### ISSUE TITLE
棉花糖系统抢红包失败

### ISSUE THREAD

**Issue by YouHolmes** [geeeeeeeeek/WeChatLuckyMoney#9]
安卓6.0，实测红包到时可见弹出框瞬间弹出并消失，但并没有领取红包。
另外，自己发的红包也不会抢，这个跟安卓6无关。

**Comment by geeeeeeeeek** [comment]
棉花糖……

确定一下你跑得时dev分支还是stable分支？dev分支有可能因为状态之间的跳转除了问题，stable分支不太可能吧。

自己发的红包可以加进去，下个版本更，周末。

**Comment by YouHolmes** [comment]
oh忘记说了我用的是stable分支，dev没用过

**Comment by geeeeeeeeek** [comment]
好的，我去复现一下，感谢提醒。
