### ISSUE TITLE
系统设置里辅助功能不能保存设定

### ISSUE THREAD

**Issue by jason1290** [geeeeeeeeek/WeChatLuckyMoney#92]
系统设置里辅助功能不能保存打开这款插件的设定，设定打开这款插件后再进去的话，还是显示没打开。
请问您知道怎么解决吗？
这个不是您这款软件的问题，其他软件，如应用宝，tasker，lbe都是这样，我的手机是S5，系统是4.4.2，网上搜了N久还是没找到解决办法，所以特别来请教下您。
我试过了，不是进程被杀掉的问题，也不是软件监控出现的问题，也不是samsungtts.apk被精简掉的问题，我也很苦恼。想看看您知不知道办法

**Comment by ray26** [comment]
Please view #86

**Comment by geeeeeeeeek** [comment]
你是说无法开启辅助服务吗？

**Comment by ray26** [comment]
这个问题应该是系统底层问题，精简掉一些东西之后也会引发这个问题

**Comment by ray26** [comment]
和apk本身应该没问题

**Comment by ray26** [comment]
你在别的系统有没有这样的情况

**Comment by jason1290** [comment]
我最新刷机，发现刷完国行的底包什么都没干，也保存不了，觉得很奇怪，一直找不到原因，很苦难这个插件用不了

**Comment by jason1290** [comment]
在安卓5.0系统里面也碰过这种情况

**Comment by jason1290** [comment]
这款插件的版本我用的是最新的2.0.1，还是不行，不是插件的问题，是系统不知道什么地方的问题

**Comment by geeeeeeeeek** [comment]
你的问题和这位的很像：
>Hey Guys! F.Y.I. Still cannot change ANYTHING under "Accessibility". My "Direct access" is "On", it allows me to set it to "Off", but when I return to Accessibility it is back "On" again. My "Single tap mode" is NOT checked, if I "Check" it when I return it is back to not being checked. Same thing on any & all of my services. Too much invested in this AT&T 5.0 instance to be willing to blow it all away and restart.

各种论坛频率最高的bug原因是装了Lux这个调光软件，大量issues由它造成。
> I found the answer for my specific case. It was Lux that was preventing me from enabling accessibility or installing from unknown sources. Sooo many factory resets and reflashing stock/rooting and it was Lux the whole time. Arggg...

另外，[三星开发者站](http://developer.samsung.com/forum/thread/samsung-devices-and-accessibility-services/77/204387)似乎有相当多关于AccessibilityService的issues。这个插件声称用不了的用户大多是三星用户，如果你确定与第三方应用无关，**珍爱生命，远离三星**。问题解决点个Star吧😃

**Comment by jason1290** [comment]
谢谢作者的解答，我再试一下看看。已经给您点星了^_^
